name: looper
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+22


environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  material_design_icons_flutter: ^4.0.5955
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  sentry_flutter: ^5.0.0
  firebase_storage: ^8.0.1
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_messaging: ^9.1.0
  firebase_auth: ^1.0.1
  google_mobile_ads: ^0.12.1
  firebase_ml_vision: ^0.11.0
  camera: ^0.8.1
  video_player: ^2.0.1
  path_provider: ^1.6.28
  image_picker: ^0.7.4
  fluttertoast: ^8.0.3
  permission_handler: ^6.1.1
  flutter_local_notifications: ^5.0.0+1
  flutter_launcher_icons: ^0.9.0
  uuid: ^2.2.2
  flutter_svg: ^0.21.0-nullsafety.0
  shimmer: ^2.0.0-nullsafety.0
  bubble: ^1.1.9+1
  badges: ^2.0.0-nullsafety.1
  intro_slider: ^2.3.4
  superellipse_shape: ^0.2.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_swiper: ^1.1.6  
  shifting_tabbar: ^1.0.1
  fab_circular_menu: ^1.0.2
  flutter_snake_navigationbar: ^0.5.0
  flutter_spinkit: "^5.0.0"
  cool_nav: ^0.0.3  
  flashy_tab_bar: ^0.0.3
  flutter_chat_bubble: ^1.0.2
  flutter_toggle_tab: ^1.0.0
  flushbar: ^1.10.4
  flutter_linkify: ^4.1.0
  flutter_bounce: ^1.0.8
  string_validator: ^0.3.0
  email_validator: ^2.0.1
  stop_watch_timer: ^1.1.0+1
  shared_preferences: ^2.0.5
  enhanced_future_builder: ^1.0.3
  cached_network_image: ^3.0.0
  flutter_image_compress: ^1.0.0
  flutter_video_compress: ^0.3.7+8
  tutorial_coach_mark: ^0.6.0+1
  flutter_sound: ^8.0.0+6
  share_plus: ^2.0.0
  location: ^4.1.1
  geocoder: ^0.2.1
  connectivity: ^2.0.2
  flutter_email_sender: ^4.0.0
  giphy_picker: ^1.0.8
  dots_indicator: ^1.2.0
  percent_indicator: ^2.1.8
  url_launcher: ^5.7.10
  intl: ^0.16.0 
  visibility_detector: ^0.1.5 
  dotted_border: ^1.0.7
  video_thumbnail: ^0.2.5+1
  file_picker: ^2.1.7
  photo_manager: ^1.0.6
  audioplayers: ^0.17.4
  export_video_frame: ^0.0.5+4
  http: ^0.12.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/looper.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_datetime_picker:
   git:
     url: https://github.com/espresso3389/flutter_datetime_picker  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/social-media (2).jpg
    - assets/tiger.jpg   
    - assets/eye.png
    - assets/clap.png
    - assets/female-hair (2).png
    - assets/male-hair (2).png
    - assets/network.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand-bold.ttf
        - asset: fonts/quicksand-bold.ttf
    #         style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.bold.ttf
        - asset: fonts/montserrat.bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
